### ISSUE TITLE
add prefix definition and update hpi example for ukhpi

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#1]
http://landregistry.data.gov.uk/def/ukhpi

**Comment by ijdickinson** [comment]
I'm presuming at the same time I should remove the definition for the old HPI prefix?

**Comment by ijdickinson** [comment]
I replaced the old hpi prefix with the new ukhpi one. This does break the current query, but Mal said he's going to look at changing the query anyway.

**Comment by ijdickinson** [comment]
Updated queries added

**Comment by ijdickinson** [comment]
@bwmcbride  I think we can close this now?

**Comment by bwmcbride** [comment]
Sure.
