### ISSUE TITLE
Qonsole internal server error when accessed via HTTPS gateway

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#11]
Qonsole is configured to POST queries to

  /app/root/qonsole/query

When the preprod service Qonsole is used to run a query, an HTTPS POST request is sent to a gateway

   lr-preprod.epimorphics.net 

which is forwarded over HTTP to the application server.

The root application rails log shows that the application tries to access

  http://lr-preprod.epimorphics.net/...

This port is not open so the connection fails.

Could the query go instead either to:

  {original-protocol}//{original-request-domain}/...

or  be routed more directly to a data server.

The http header X-Forwarded-Scheme is set on the original request, if it comes through a gateway.

**Comment by ijdickinson** [comment]
Google doesn't reveal much for `X-Forwarded-Scheme`. Do you mean `X-Forwarded-Proto`?

**Comment by ijdickinson** [comment]
Moved to `qonsole-rails` https://github.com/epimorphics/qonsole-rails/issues/9
