### ISSUE TITLE
Landing - Ensure links are distinguished

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/lr-landing#126]
Ensure links are distinguished from surrounding text in a way that does not rely on color

Please see spreadsheet https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=188486077#gid=188486077&range=A5

**Comment by DanielCouzens** [comment]
@tomguilbert this is ready to check on the dev instance https://hmlr-dev-pres.epimorphics.net/

**Comment by tomguilbert** [comment]
Cookie banner just needs doing too

**Comment by DanielCouzens** [comment]
Finishing this ticket off requires updating a separate repo. [lr_common_styles](https://github.com/epimorphics/lr_common_styles) as we need to add underlines to the link text in the cookies banner.

**Comment by tomguilbert** [comment]
OK thanks @DanielCouzens I can see this has been applied to the cookie banner as well now so closing
