### ISSUE TITLE
Script load fails when page accessed over https

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#13]
Some scripts have urls of the form http://....

Loading these scripts is blocked if the page was retrieved using https.

Two that show up in the integration tests are:

https://lr-ppd-dev-pres.epimorphics.net/ppd-data.html
https://lr-ppd-dev-pres.epimorphics.net/fees-calculator.html

**Comment by ijdickinson** [comment]
@bwmcbride I think this now works on dev (it still gives an error from ppd-data, but I think that's actually because LR are calling an API ... `timeapi.org` ... that is now dead.

**Comment by bwmcbride** [comment]
Confirmed fixed.  Thank you.
