### ISSUE TITLE
Update Accessibility Statement Copy

### ISSUE THREAD

**Issue by tomguilbert** [epimorphics/lr-landing#136]
Update copy of English and Welsh Accessibility Statements:

https://docs.google.com/document/d/1JdZ04eD919f9AlAd5awYrzztODCfHkrz/edit#heading=h.gjdgxs

**Comment by bogdanadrianmarc** [comment]
@tomguilbert  The changes should be on the dev instance soon, if all looks good to you I'm happy to close this 👍

**Comment by tomguilbert** [comment]
@bogdanadrianmarc - you have linked to a GH user that isn't me :)

Also, the new copy hasn't come across properly - for both the English and Welshe it is cut off early

**Comment by bogdanadrianmarc** [comment]
@tomguilbert This seems to happen an illegal amount of times lately 🙂 I fixed the issues with both, they were caused by the HTML tags in the statement not being escaped. Should shortly show up on the dev instance 👍

**Comment by tomguilbert** [comment]
Thanks @bogdanadrianmarc this looks good now. Can you push this up to pre-prod next week please?

**Comment by bogdanadrianmarc** [comment]
The changes are now up to `preprod`: https://hmlr-preprod-pres.epimorphics.net/accessibility

**Comment by tomguilbert** [comment]
Great thanks @bogdanadrianmarc
