### ISSUE TITLE
Link to HPI app is /app/hpi instead of /app/ukhpi

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#2]
On the landing page "/" there is a link to /app/hpi.

**Comment by ijdickinson** [comment]
Not enough information. Where are you seeing the old link?

**Comment by bwmcbride** [comment]
My bad. Its on the landing page "/"

ps: I've just updated what I thought was the description but is in fact my original comment.

**Comment by bwmcbride** [comment]
responding to your comment in slack:

The one I originally found is in the text "Use Search the House Price Index to find:" under the heading 

"Search the House Price Index"

A grep of the source of the page reveals another with the text:

Search the house price index

under heading 

Bespoke reports

**Comment by bwmcbride** [comment]
Fixed.
