### ISSUE TITLE
500 error on SPARQL form query that returns non-ascii UTF8 chars

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#21]
I'm seeing a 500 error when I enter the following query into the sparql form on https://landregistry.data.gov.uk (and also on the dev server)

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>

select * {
  ?region a ukhpi:Region ;
          rdfs:label ?label ;
          .
}
```

Comment out the label line and the query succeeds.

**Comment by bwmcbride** [comment]
Looking at the logs - the query is reaching Fuseki, being processed and returning a 200 response.

In the rails app production.log (on dev) I find:

[[
I, [2020-02-07T12:03:31.833409 #27542]  INFO -- : Started POST "/app/root/qonsole/query" for 213.123.52.202 at 2020-02-07 12:03:31 +0000
I, [2020-02-07T12:03:31.834229 #27542]  INFO -- : Processing by QonsoleRails::QonsoleController#create as */*
I, [2020-02-07T12:03:31.834363 #27542]  INFO -- :   Parameters: {"output"=>"tsv", "url"=>"/landregistry/query", "q"=>"prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nprefix ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>\n\nselect * {\n  ?region a ukhpi:Region ;\n          rdfs:label ?label ;\n          .\n}"}
I, [2020-02-07T12:03:31.835521 #27542]  INFO -- request: POST http://10.0.0.203/landregistry/query
D, [2020-02-07T12:03:31.835626 #27542] DEBUG -- request: User-Agent: "Faraday v0.17.1"
Accept: "text/tab-separated-values"
Content-Type: "application/x-www-form-urlencoded"
I, [2020-02-07T12:03:31.846857 #27542]  INFO -- response: Status 200
D, [2020-02-07T12:03:31.847006 #27542] DEBUG -- response: date: "Fri, 07 Feb 2020 12:03:31 GMT"
server: "Apache"
fuseki-request-id: "136"
cache-control: "must-revalidate,no-cache,no-store"
pragma: "no-cache"
content-type: "text/tab-separated-values; charset=utf-8"
connection: "close"
transfer-encoding: "chunked"
W, [2020-02-07T12:03:31.847735 #27542]  WARN -- : No explicit error page for exception "\xC3" from ASCII-8BIT to UTF-8 - Encoding::UndefinedConversionError
I, [2020-02-07T12:03:31.848208 #27542]  INFO -- :   Rendering public/500.html
I, [2020-02-07T12:03:31.848415 #27542]  INFO -- :   Rendered public/500.html (0.1ms)
I, [2020-02-07T12:03:31.848634 #27542]  INFO -- : Completed 500 Internal Server Error in 14ms (Views: 0.6ms)
]]

**Comment by bwmcbride** [comment]
The query works through the Fuseki interface and it works on some (specific) regions, e.g.

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>
SELECT * {
  <http://landregistry.data.gov.uk/id/region/nottinghamshire> 
#  <http://landregistry.data.gov.uk/id/region/leicester>
#  <http://landregistry.data.gov.uk/id/region/leicestershire>
    a ukhpi:Region ;
    rdfs:label ?label ;
    .
}      

works.  But the two commented out regions fail.  Both contain an accented character in the label.

**Comment by ijdickinson** [comment]
@bwmcbride Looking at the tsv output, which is what Qonsole is requesting when outputting a table:

    $ curl -X POST -H "Content-type: application/sparql-query" --data-binary @test.rq \
    'http://lr-ppd-dev-data-1.epimorphics.net/landregistry/query?output=tsv'
    ?label
    "Leicester"@en
    "Caerl R"@cy
    "Caerlŷr"@cy

Neither of those values look like valid `@cy` strings and there are unexpectedly two Welsh labels for one location.

Has there been a change in the Fuseki version being used? Could the TSV renderer have changed? (which wouldn't explain the 2x labels, but might say why Welsh lang strings are suddenly coming out mangled)

**Comment by bwmcbride** [comment]
A Google search suggests at least the one with the accented 'y' is correct:

  https://www.google.com/search?q=welsh+for+leicester&oq=welsh+for+leicester

There are some google matches for something similar to the other form but rendered as "Caerl?r".  

Fuseki was last updated 6 months ago.  I have no idea if this issue occurred before or after that.

I think its more general than TSV.  If I run the query:

  <http://landregistry.data.gov.uk/id/region/leicester>

it barfs.  That query will return an RDF format (I think ttl by default).

I tried using iconv per https://stackoverflow.com/questions/115210/how-to-check-whether-a-file-is-valid-utf-8 to validate the file returned by the query and it passed.

I am having some deja vu about this.  We have seen issues in this area before.

**Comment by bwmcbride** [comment]
Per our conversation in the kitchen, I've taken a look at data returned from the query at the byte level.

It looks valid to me.  The file consists of all ascii chararacters except for one 2 byte pair:

  305 267 (octal)

According to https://en.wikipedia.org/wiki/UTF-8 this maps to unicode code point 0567 (octal) which U+0177 which is a lowercase y with a circumflex - https://www.compart.com/en/unicode/U+0177

**Comment by ijdickinson** [comment]
@bwmcbride Fix applied to dev, if you'd like to QA

**Comment by bwmcbride** [comment]
@ijdickinson Done.  Looks good.  I'm not sure if you click click the close button or I do?

I will be doing routine updates on LR soon anyway - I can roll out to the other servers when I do that if it helps.
