### ISSUE TITLE
Qonsole failing in virtual box environment

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#3]
Looks like its having trouble resolving the DNS name of the SPARQL endpoint its trying to access.  This could be because the DNS name used in the tests is only defined on the test client machine - as it is pointing to a 10.10.10.10 address.

Would it be possible for the query to go to localhost?

**Comment by ijdickinson** [comment]
The relevant part of the configuration file (`qonsole.json`) is:

    "endpoints": {
      "default": "/landregistry/query",
      "dev": "http://lr-pres-dev-c.epimorphics.net/landregistry/query"
    },

So the `default` is already going to localhost. Assuming your test is not selecting the `dev` endpoint, rather than `default`, the problem must lie within your VirtualBox setup.

**Comment by ijdickinson** [comment]
I suppose you could try putting your own `qonsole.json` file in place, with e.g. an explicit mention of localhost or 127.0.0.1 for the endpoint, to see if that sheds any light.

**Comment by bwmcbride** [comment]
Thanks for the pointer.   Its working again now.  No need for you to change anything.
