### ISSUE TITLE
404 errors from fees-calcultor page

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#4]
The page /fees-calculator.html has an image src'd from /new_window.gif that is 404'ing.  There are three occurrences which searching the page source will find.

This is an error also on the current publication server.  It leads to a lot of 404 errors in the logs which means we can't reliably set alarms on the number of 404 errors being generated.

**Comment by ijdickinson** [comment]
I could only find one image `src` attribute which referred to an incorrect path. Happy to correct others if you can point me to them. This is not code that I manage, we only publish it, so I'll have to get the change pushed upstream otherwise it will come back next time we get an update from Simon.

**Comment by bwmcbride** [comment]
There was only one - I think I previously found a class attribute name rather than an image src. 

Confirm fixed.
