### ISSUE TITLE
Readme is out of date.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/lr-landing#65]
The Readme even in the dev-infrastructure branch still makes reference to Chef. 

I would also expect a description of the interface this provides, or link to same elsewhere.
For example the environment variables it uses/requires and what they represent.
The expected endpoints of application/requirements in configuring any proxy, metrics or health checks to assit in configuring monitoring.

**Comment by ijdickinson** [comment]
Closed here and refiled in the shared issues list: https://github.com/epimorphics/hmlr-linked-data/issues/53
