### ISSUE TITLE
Javascript syntax error on /ppd-data.html

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/lr-landing#8]
The CI server is failing reporting a javascript error when accessing /ppd-data.html

**Comment by ijdickinson** [comment]
What is the error? Where is the error log? I looked at the epi-jenkins server and I can't even see the job listed.

**Comment by bwmcbride** [comment]
To reproduce, visit:

  http://landregistry.data.gov.uk/ppd-data.html  

the console reports an error

  Uncaught SyntaxError: Unexpected token <

The job is not on the epi-jenkins server.  Its a cookbook test that runs the integration tests after running the cookbook.  I use the local jenkins in for cookbook ci tests so that it can fire up VMs.

**Comment by ijdickinson** [comment]
I can't reproduce the problem by visiting that URL in either Chrome or Firefox.

It's also code that is owned by LR, not me, (we just host it for them) and hasn't changed in months. Could it be a problem with the test environment?

**Comment by ijdickinson** [comment]
On investigation, this seems to be a problem with an external time service that is returning HTML instead of a JSON/JavaScript payload. I have reported the issue to the upstream code owner to request a fix. In the meantime, we have discussed disabling the specific CI test that is failing.

**Comment by bwmcbride** [comment]
Specific test disabled in CI only.  Please let me know when it can be reenabled.

Please feel free to close this or leave open as a reminder - your call.

**Comment by ijdickinson** [comment]
@bwmcbride I think that this might have been silently fixed: visiting the page, I don't see a JS console warning. Do you want to try re-enabling the CI check?

**Comment by bwmcbride** [comment]
I'm still seeing an error - an access refused message.

However, this is not triggering a test failure.

Test re-enabled in CI
